// Dummy data for citizen reports
export const reportsDummy = [
  {
    id: 'RPT-001',
    citizen: 'Juan Dela Cruz',
    type: 'Road Issues',
    description: 'Large pothole on Main Street causing traffic delays',
    location: 'Main St. & 5th Ave',
    priority: 'High',
    status: 'In Progress',
    dateSubmitted: '2025-01-20',
    assignedTo: 'Public Works Dept.',
  },
  {
    id: 'RPT-002',
    citizen: 'Maria Santos',
    type: 'Public Safety',
    description: 'Broken streetlight in residential area',
    location: 'Oak Street Block 12',
    priority: 'Medium',
    status: 'Pending',
    dateSubmitted: '2025-01-19',
    assignedTo: 'Electrical Maintenance',
  },
  {
    id: 'RPT-003',
    citizen: 'Roberto Garcia',
    type: 'Environmental',
    description: 'Illegal dumping site near river',
    location: 'Riverside Park Area',
    priority: 'Critical',
    status: 'Resolved',
    dateSubmitted: '2025-01-18',
    assignedTo: 'Environmental Unit',
  },
  {
    id: 'RPT-004',
    citizen: 'Ana Lopez',
    type: 'Infrastructure',
    description: 'Water leak affecting multiple households',
    location: 'Pine Ave Block 8',
    priority: 'High',
    status: 'In Progress',
    dateSubmitted: '2025-01-17',
    assignedTo: 'Water Department',
  },
  {
    id: 'RPT-005',
    citizen: 'Carlos Mendoza',
    type: 'Public Transport',
    description: 'Bus stop sign damaged and unreadable',
    location: 'Central Bus Terminal',
    priority: 'Low',
    status: 'Pending',
    dateSubmitted: '2025-01-16',
    assignedTo: 'Transportation Office',
  },
  {
    id: 'RPT-006',
    citizen: 'Sofia Reyes',
    type: 'Utilities',
    description: 'Power outage affecting residential block',
    location: 'Maple Street Block 15',
    priority: 'Critical',
    status: 'Resolved',
    dateSubmitted: '2025-01-15',
    assignedTo: 'Power Company',
  },
]
